# Generated by Django 4.0.3 on 2022-05-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='auto_id',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='auto_id',
            new_name='user_id',
        ),
    ]
