# Generated by Django 3.1.1 on 2022-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220207_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('D', 'Divorced'), ('M', 'Married'), ('S', 'Single')], default='S', max_length=1),
        ),
    ]
