# Generated by Django 4.0.3 on 2022-05-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='marital_status',
        ),
    ]
