# Generated by Django 4.0.3 on 2022-05-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='auto_id',
            new_name='job_id',
        ),
    ]
