# Generated by Django 4.0.3 on 2022-06-05 20:06

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='image',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(default=2, max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=employees.models.file_folder),
        ),
    ]
