# Generated by Django 4.0.3 on 2022-05-30 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='auto_id',
            new_name='attendance_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='auto_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='auto_id',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='auto_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='auto_id',
            new_name='holiday_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='auto_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='auto_id',
            new_name='task_id',
        ),
    ]
