# Generated by Django 3.1.1 on 2022-02-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_employed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
