# Generated by Django 3.1.1 on 2022-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20220202_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('OL', 'On Leave')], default='A', max_length=2),
        ),
    ]
