# Generated by Django 4.0.3 on 2022-06-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_projectfile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='name',
            field=models.CharField(default='First Files in', max_length=255),
            preserve_default=False,
        ),
    ]
