# Generated by Django 4.0.3 on 2022-05-26 02:22

from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_project_completed_project_verified_task_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='To be used if file is an image', null=True, upload_to=employees.models.file_folder)),
                ('file', models.FileField(blank=True, help_text='To be used if file is a document, audio or video', null=True, upload_to=employees.models.file_folder)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.project')),
            ],
        ),
    ]
