# Generated by Django 3.1.1 on 2022-02-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20220203_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('A', 'Annual'), ('C', 'Causal'), ('H', 'Hospitalization'), ('LOP', 'Loss Of Pay'), ('M', 'Maternity'), ('P', 'Paternity'), ('S', 'Sick')], max_length=3, verbose_name='type')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1)),
                ('approved_by_admin', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1)),
                ('approved_by_hr', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1)),
                ('approved_by_md', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to='employees.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
    ]
