# Generated by Django 4.0.3 on 2022-06-06 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_projectfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.project'),
        ),
    ]
