# Generated by Django 3.1.1 on 2022-02-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20220208_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by_hr',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by_md',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
        migrations.AddField(
            model_name='leave',
            name='a_hod',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by HOD'),
        ),
        migrations.AddField(
            model_name='leave',
            name='a_hr',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by HR'),
        ),
        migrations.AddField(
            model_name='leave',
            name='a_md',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by MD'),
        ),
        migrations.AddField(
            model_name='leave',
            name='a_s',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by Supervisor'),
        ),
    ]
