# Generated by Django 4.0.3 on 2022-06-11 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_projectfile_date_alter_projectfile_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='employees.employee', unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
