# Generated by Django 3.1.1 on 2022-02-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20220208_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='to_date',
            new_name='start_date',
        ),
    ]
