# Generated by Django 4.0.3 on 2022-06-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='verified',
        ),
    ]
