# Generated by Django 3.1.1 on 2022-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20220210_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
