# Generated by Django 3.1.1 on 2022-02-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
