# Generated by Django 3.1.1 on 2022-02-16 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20220215_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_md',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_employed',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 14, 9, 7, 251019, tzinfo=utc)),
        ),
    ]
