# Generated by Django 3.1.1 on 2022-02-16 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20220216_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_employed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
