# Generated by Django 3.1.1 on 2022-02-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0012_auto_20220216_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='a_hod',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by HOD'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='a_hr',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by HR'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='a_md',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by MD'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='a_s',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by Supervisor'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
