# Generated by Django 3.1.1 on 2022-02-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20220217_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
