# Generated by Django 3.1.1 on 2022-03-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.job'),
        ),
    ]
