# Generated by Django 4.0.3 on 2022-03-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('employees', '0018_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
