# Generated by Django 4.0.3 on 2022-03-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_department_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to='employees.employee'),
        ),
    ]
