# Generated by Django 4.0.3 on 2022-05-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_company_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
