# Generated by Django 4.0.3 on 2022-05-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='title',
            new_name='name',
        ),
    ]
