# Generated by Django 4.0.3 on 2022-05-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_rename_title_holiday_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date')},
        ),
    ]
