# Generated by Django 4.0.3 on 2022-03-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0018_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('A', 'Annual'), ('C', 'Causal'), ('H', 'Hospitalization'), ('LOP', 'Loss Of Pay'), ('M', 'Maternity'), ('P', 'Paternity'), ('S', 'Sick')], max_length=3, verbose_name='type')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1)),
                ('a_s', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by Supervisor')),
                ('a_hod', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by HOD')),
                ('a_hr', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by HR')),
                ('a_md', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('N', 'Not Needed'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Approved by MD')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_check', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_check', to='employees.employee')),
            ],
        ),
    ]
