# Generated by Django 4.0.3 on 2022-05-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='auto_id',
            new_name='leave_id',
        ),
    ]
