# Generated by Django 4.0.3 on 2022-03-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_remove_leave_created_by_remove_leave_employee_and_more'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee'),
        ),
    ]
