# Generated by Django 4.0.3 on 2022-06-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_attendance_unique_together_and_more'),
        ('leaves', '0002_overtime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtime',
            unique_together={('employee', 'date')},
        ),
    ]
