# Generated by Django 4.0.3 on 2022-03-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leave_created_by_alter_leave_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
    ]
