# Generated by Django 4.0.3 on 2022-06-11 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_attendance_unique_together_and_more'),
        ('leaves', '0003_alter_overtime_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtime',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='employees.employee', unique_for_date='date'),
        ),
    ]
