# Generated by Django 4.0.3 on 2022-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_overtime_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('A', 'Annual'), ('C', 'Causal'), ('H', 'Hospitalization'), ('LOP', 'Loss Of Pay'), ('M', 'Maternity'), ('P', 'Paternity'), ('S', 'Sick')], default='C', max_length=3, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='overtime_type',
            field=models.CharField(choices=[('C', 'Compulsory'), ('H', 'Holiday'), ('V', 'Voluntary')], default='V', max_length=3, verbose_name='type'),
        ),
    ]
