# Generated by Django 4.0.3 on 2022-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='_type',
            field=models.CharField(choices=[('L', 'Leave'), ('O', 'Overtime')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_id',
            field=models.CharField(max_length=10),
        ),
    ]
