# Generated by Django 3.1.1 on 2022-02-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(default='k', max_length=100),
            preserve_default=False,
        ),
    ]
