# Generated by Django 3.1.1 on 2022-02-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='recepient',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='_from',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='_to',
            field=models.EmailField(max_length=100),
        ),
    ]
