# Generated by Django 3.1.1 on 2022-02-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
