# Generated by Django 3.1.1 on 2022-02-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20220217_1054'),
        ('notifications', '0005_auto_20220220_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='_to',
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='employees.employee'),
        ),
    ]
