# Generated by Django 3.1.1 on 2022-02-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20220220_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='seen',
            new_name='read',
        ),
    ]
