# Generated by Django 3.1.1 on 2022-02-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20220220_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='subject',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
